-- Duckling updated schema
-- Run on a fresh/dev Supabase database, or adapt carefully for existing data.

create extension if not exists pgcrypto;

drop table if exists public.submissions cascade;
drop table if exists public.test_cases cascade;
drop table if exists public.problem_implementations cascade;
drop table if exists public.assignments cascade;
drop table if exists public.enrollments cascade;
drop table if exists public.batch_progress cascade;
drop table if exists public.batch_milestones cascade;
drop table if exists public.classes cascade;
drop table if exists public.batches cascade;
drop table if exists public.problems cascade;
drop table if exists public.users cascade;

create table public.users (
  id uuid primary key default gen_random_uuid(),
  email varchar(255) not null unique,
  username varchar(50) not null unique,
  password_hash varchar(255) not null,

  display_name varchar(80),
  role varchar(30) not null default 'student'
    check (role in ('student', 'teacher', 'student-teacher')),
  school_name varchar(120),
  bio varchar(280),

  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp,
  deleted_at timestamp
);

create table public.problems (
  id bigint primary key,
  slug varchar(255) not null unique,
  title varchar(255) not null,
  description text not null,
  difficulty varchar(20) not null check (difficulty in ('Easy', 'Medium', 'Hard')),

  language varchar(50) not null,
  topic varchar(100) not null,
  category varchar(100),
  problem_set varchar(120) not null,
  batch_name varchar(160) not null,
  tags text[] not null default '{}',
  acceptance numeric(5,2),

  estimated_time_minutes integer check (estimated_time_minutes > 0),
  is_published boolean not null default true,
  created_by uuid references public.users(id) on delete set null,

  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp,
  version integer not null default 1 check (version > 0)
);

create table public.batches (
  id bigint generated by default as identity primary key,
  name varchar(255) not null,
  description text,
  problem_set varchar(120) not null,
  language varchar(50),
  skill_level varchar(50),
  tags text[] not null default '{}',
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp,
  unique(problem_set, name)
);

create table public.batch_milestones (
  id bigint generated by default as identity primary key,
  batch_id bigint not null references public.batches(id) on delete cascade,
  problem_id bigint not null references public.problems(id) on delete cascade,
  order_index integer not null check (order_index > 0),
  is_prerequisite boolean not null default false,
  created_at timestamp not null default current_timestamp,
  unique(batch_id, problem_id),
  unique(batch_id, order_index)
);

create table public.batch_progress (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.users(id) on delete cascade,
  batch_id bigint not null references public.batches(id) on delete cascade,
  milestone_id bigint not null references public.batch_milestones(id) on delete cascade,
  status varchar(50) not null default 'locked',
  completed_at timestamp,
  created_at timestamp not null default current_timestamp,
  unique(student_id, milestone_id)
);

create table public.classes (
  id uuid primary key default gen_random_uuid(),
  teacher_id uuid not null references public.users(id) on delete cascade,
  name varchar(255) not null,
  description text,
  code varchar(20) not null unique,
  language_focus varchar(50),
  is_active boolean not null default true,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp
);

create table public.enrollments (
  id bigint generated by default as identity primary key,
  class_id uuid not null references public.classes(id) on delete cascade,
  student_id uuid not null references public.users(id) on delete cascade,
  enrolled_at timestamp not null default current_timestamp,
  unique(class_id, student_id)
);

create table public.assignments (
  id bigint generated by default as identity primary key,
  class_id uuid not null references public.classes(id) on delete cascade,
  problem_id bigint not null references public.problems(id) on delete cascade,
  title varchar(255),
  instructions text,
  pack_id varchar(180),
  assigned_at timestamp not null default current_timestamp,
  due_at timestamp,
  created_by uuid not null references public.users(id) on delete cascade,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp
);

create table public.problem_implementations (
  id bigint generated by default as identity primary key,
  problem_id bigint not null references public.problems(id) on delete cascade,
  language varchar(50) not null,
  skeleton_code text,
  solution_code text,
  hidden_code text,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp,
  unique(problem_id, language)
);

create table public.test_cases (
  id bigint generated by default as identity primary key,
  problem_id bigint not null references public.problems(id) on delete cascade,
  language varchar(50),
  input_json text not null,
  expected_output_json text not null,
  is_hidden boolean not null default false,
  created_at timestamp not null default current_timestamp
);

create table public.submissions (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.users(id) on delete cascade,
  problem_id bigint not null references public.problems(id) on delete cascade,
  assignment_id bigint references public.assignments(id) on delete set null,
  language varchar(50) not null,
  code text not null,
  submission_type varchar(50) not null default 'practice',
  status varchar(50) not null default 'draft',
  result varchar(50),
  execution_time_ms integer check (execution_time_ms > 0),
  memory_used_mb integer check (memory_used_mb > 0),
  passed_tests integer check (passed_tests >= 0),
  total_tests integer check (total_tests > 0),
  output_json text,
  error_message text,
  job_id varchar(255),
  submitted_at timestamp not null default current_timestamp,
  completed_at timestamp,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp
);

create index idx_problems_set_batch on public.problems(problem_set, batch_name);
create index idx_problems_topic on public.problems(topic);
create index idx_problems_language on public.problems(language);
create index idx_classes_teacher on public.classes(teacher_id);
create index idx_classes_code on public.classes(code);
create index idx_enrollments_student on public.enrollments(student_id);
create index idx_assignments_class on public.assignments(class_id);
create index idx_assignments_problem on public.assignments(problem_id);
create index idx_submissions_student on public.submissions(student_id);
create index idx_submissions_problem on public.submissions(problem_id);