-- Duckling Supabase schema patch.
-- Run this in the Supabase SQL editor, then seed problems with:
--   cd backend && python3 scripts/seed_problems.py
--
-- The assignment foreign key error happens when assignments.problem_id points
-- at a Duckling catalog id that has not been inserted into public.problems.

create extension if not exists pgcrypto;

alter table if exists public.users
  add column if not exists display_name text,
  add column if not exists role text not null default 'student',
  add column if not exists school_name text,
  add column if not exists bio text,
  add column if not exists deleted_at timestamp without time zone;

create table if not exists public.problems (
  id bigint primary key,
  slug character varying(255) not null unique,
  title character varying(255) not null,
  description text not null,
  difficulty character varying(20) not null,
  language character varying(50) not null default 'Java',
  topic character varying(100),
  category character varying(100),
  problem_set character varying(120),
  batch_name character varying(160),
  tags text[] not null default '{}',
  acceptance numeric(5,2),
  estimated_time_minutes integer check (estimated_time_minutes > 0),
  is_published boolean not null default true,
  created_by uuid references public.users(id) on delete set null,
  created_at timestamp without time zone not null default current_timestamp,
  updated_at timestamp without time zone not null default current_timestamp,
  version integer not null default 1 check (version > 0)
);

create sequence if not exists public.problems_id_seq owned by public.problems.id;
alter table public.problems alter column id set default nextval('public.problems_id_seq'::regclass);

alter table if exists public.problems
  add column if not exists language character varying(50) not null default 'Java',
  add column if not exists topic character varying(100),
  add column if not exists problem_set character varying(120),
  add column if not exists batch_name character varying(160),
  add column if not exists tags text[] not null default '{}',
  add column if not exists acceptance numeric(5,2);

create table if not exists public.classes (
  id bigint primary key generated by default as identity,
  teacher_id uuid not null references public.users(id) on delete cascade,
  name character varying(255) not null,
  description text,
  code character varying(20) not null unique,
  language_focus character varying(50),
  is_active boolean not null default true,
  created_at timestamp without time zone not null default current_timestamp,
  updated_at timestamp without time zone not null default current_timestamp
);

create table if not exists public.enrollments (
  id bigint primary key generated by default as identity,
  class_id bigint not null references public.classes(id) on delete cascade,
  student_id uuid not null references public.users(id) on delete cascade,
  enrolled_at timestamp without time zone not null default current_timestamp,
  unique (class_id, student_id)
);

create table if not exists public.assignments (
  id bigint primary key generated by default as identity,
  class_id bigint not null references public.classes(id) on delete cascade,
  problem_id bigint not null references public.problems(id) on delete restrict,
  title character varying(255),
  instructions text,
  assigned_at timestamp without time zone not null default current_timestamp,
  due_at timestamp without time zone,
  created_by uuid not null references public.users(id) on delete cascade,
  created_at timestamp without time zone not null default current_timestamp,
  updated_at timestamp without time zone not null default current_timestamp
);

create table if not exists public.batches (
  id bigint primary key generated by default as identity,
  name character varying(255) not null,
  description text,
  language character varying(50),
  skill_level character varying(50),
  created_at timestamp without time zone not null default current_timestamp,
  updated_at timestamp without time zone not null default current_timestamp
);

create table if not exists public.batch_milestones (
  id bigint primary key generated by default as identity,
  batch_id bigint not null references public.batches(id) on delete cascade,
  problem_id bigint not null references public.problems(id) on delete cascade,
  order_index integer not null check (order_index > 0),
  is_prerequisite boolean not null default false,
  created_at timestamp without time zone not null default current_timestamp,
  unique (batch_id, problem_id)
);

create table if not exists public.batch_progress (
  id bigint primary key generated by default as identity,
  student_id uuid not null references public.users(id) on delete cascade,
  batch_id bigint not null references public.batches(id) on delete cascade,
  milestone_id bigint not null references public.batch_milestones(id) on delete cascade,
  status character varying(50) not null default 'locked',
  completed_at timestamp without time zone,
  created_at timestamp without time zone not null default current_timestamp,
  unique (student_id, milestone_id)
);

create table if not exists public.problem_implementations (
  id bigint primary key generated by default as identity,
  problem_id bigint not null references public.problems(id) on delete cascade,
  language character varying(50) not null,
  skeleton_code text,
  solution_code text,
  hidden_code text,
  created_at timestamp without time zone not null default current_timestamp,
  updated_at timestamp without time zone not null default current_timestamp,
  unique (problem_id, language)
);

create table if not exists public.submissions (
  id bigint primary key generated by default as identity,
  student_id uuid not null references public.users(id) on delete cascade,
  problem_id bigint not null references public.problems(id) on delete cascade,
  assignment_id bigint references public.assignments(id) on delete set null,
  language character varying(50) not null,
  code text not null,
  submission_type character varying(50) not null default 'practice',
  status character varying(50) not null default 'draft',
  result character varying(50),
  execution_time_ms integer check (execution_time_ms > 0),
  memory_used_mb integer check (memory_used_mb > 0),
  passed_tests integer check (passed_tests >= 0),
  total_tests integer check (total_tests > 0),
  output_json text,
  error_message text,
  job_id character varying(255),
  submitted_at timestamp without time zone not null default current_timestamp,
  completed_at timestamp without time zone,
  created_at timestamp without time zone not null default current_timestamp,
  updated_at timestamp without time zone not null default current_timestamp
);

create table if not exists public.test_cases (
  id bigint primary key generated by default as identity,
  problem_id bigint not null references public.problems(id) on delete cascade,
  language character varying(50),
  input_json text not null,
  expected_output_json text not null,
  is_hidden boolean not null default false,
  created_at timestamp without time zone not null default current_timestamp
);

create index if not exists idx_classes_teacher_id on public.classes(teacher_id);
create index if not exists idx_classes_code on public.classes(code);
create index if not exists idx_enrollments_student_id on public.enrollments(student_id);
create index if not exists idx_assignments_class_id on public.assignments(class_id);
create index if not exists idx_assignments_problem_id on public.assignments(problem_id);
create index if not exists idx_submissions_student_id on public.submissions(student_id);
create index if not exists idx_submissions_problem_id on public.submissions(problem_id);

select setval(
  'public.problems_id_seq',
  greatest((select coalesce(max(id), 1) from public.problems), 1),
  true
);
